### ISSUE TITLE
to-do list _ 2019

### ISSUE THREAD

**Issue by epsimatt** [epsimatt/byte-of-python#15]
note: tasks with the checkboxes ticked are pages that are currently being worked on.

https://epsimatt.gitbook.io/byte-of-python/

- [x] 소개
- [x] 첫 번째 프로그램 만들기
- [x] 파이썬 기초 지식
- [x] 연산자와 수식
- [ ] 프로그램 제어와 구조화
- [x] 함수
- [ ] 모듈
- [x] 자료 구조란?
- [ ] 실용적 프로그램 만들기
- [ ] 객체 지향 프로그래밍
- [ ] 입력과 출력
- [ ] 예외란?
- [x] 표준 라이브러리
- [ ] 여러가지 유용한 기능 배우기
- [ ] 그 다음은?
- [ ] 부록: FLOSS
- [ ] 부록: 책 정보
- [ ] 부록: 책 업데이트 내역
