### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by epsimatt** [epsimatt/byte-of-python#2]
- [ ] 소개
- [ ] 헌사
- [ ] 머리말
- [ ] 파이썬, 누구냐 넌
- [ ] 파이썬 설치하기
- [ ] 첫 번째 프로그램 만들기
- [ ] 파이썬 기초 지식
- [ ] 연산자와 수식
- [ ] 프로그램 제어와 구조화
- [ ] 함수
- [ ] 모듈
- [ ] 자료 구조란?
- [ ] 실용적 프로그램 만들기
- [ ] 객체 지향 프로그래밍 (Object-Oriented Programming)
- [ ] 입력과 출력
- [ ] 예외란?
- [ ] 표준 라이브러리
- [ ] 여러가지 유용한 기능 배우기
- [ ] 그 다음은?
- [ ] 부록: FLOSS
- [ ] 부록: 책 정보
- [ ] 부록: 책 업데이트 내역
